/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/matcha/matchaTheme.ts
 * Command: astryx theme build src/themes/matcha/matchaTheme.ts --out src/themes/matcha/matcha.css
 * Generated: 2026-08-04T16:19:17.341Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const matchaIconRegistry: IconRegistry;
export declare const matchaTheme: DefinedTheme;
