/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/garden/gardenTheme.ts
 * Command: astryx theme build src/themes/garden/gardenTheme.ts --out src/themes/garden/garden.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.2.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const gardenIconRegistry: IconRegistry;
export declare const gardenTheme: DefinedTheme;
